#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPT_DIR=`pwd`
popd > /dev/null

# Set CANVAS_DIR if not set in the environment
: ${CANVAS_DIR:="$SCRIPT_DIR/../canvas-lms"}

# [OPTIONAL]: Build the Canvas API docs and corresponding JSON files.
#
# Comment this out if you don't want to re-generate the Canvas API spec.
# set -x
# cd "$CANVAS_DIR" && (
#   set +x
#   echo `pwd`
#   set -x
#   CANVAS_DOMAIN="https://canvas.instructure.com" bundle exec rake doc:api
# )

# [OPTIONAL]: Remove the pandarus/api directory and re-populate it with JSON
# files from the Canvas "rake doc:api" process.
#
# Comment this out if you don't want to overwrite the Pandarus gem's built-in
# Canvas API spec.
cd "$SCRIPT_DIR" && (
  set +x
  echo `pwd`
  set -x
  rm -rf ./api &&
  mkdir api &&
  cp ${CANVAS_DIR}/public/doc/api/*.json api/
	git checkout -- api/account_reports.json
	git checkout -- api/admins.json
	git checkout -- api/courses.json
	git checkout -- api/notification_preferences.json
	git checkout -- api/quiz_submission_questions.json
	git checkout -- api/sections.json
	git checkout -- api/sis_imports.json
	git checkout -- api/submissions.json
	git checkout -- api/tabs.json
	git checkout -- api/user_observees.json
	git checkout -- api/users.json
  rm api/analytics.json
	rm api/announcements.json
	rm api/authentication_providers.json
	rm api/blueprint_courses.json
	rm api/blueprint_templates.json
	rm api/bookmarks.json
	rm api/brand_configs.json
	rm api/e_pub_exports.json
	rm api/error_reports.json
	rm api/jw_ts.json
	rm api/late_policy.json
	rm api/moderated_grading.json
	rm api/originality_reports.json
	rm api/peer_reviews.json
	rm api/plagiarism_detection_platform_users.json
	rm api/planner_note.json
	rm api/planner_override.json
	rm api/rubrics.json
	rm api/shared_brand_configs.json
	rm api/sis_integration.json
	rm api/webhooks_subscriptions.json
  ruby normalize-manifest
)

# Build the Ruby gem and install it locally
cd "$SCRIPT_DIR" && (
  set +x
  echo `pwd`
  echo "rm -f ./clients/ruby/lib/pandarus/models/*.rb"
  rm -f ./clients/ruby/lib/pandarus/models/*.rb

  set -x
  mvn clean package scala:run -Dlauncher=ruby-codegen &&
  (
    cd clients/ruby
    GEMFILE=$(gem build pandarus.gemspec | fgrep -i 'FILE:' | awk '{ print $2 }')
    gem install $GEMFILE
  )

  pushd clients/ruby
  bundle exec rspec
  popd
)
