#!/bin/bash

set -x

cd "$( dirname "${BASH_SOURCE[0]}" )" && (

  rm -f ./clients/ruby/lib/pandarus/models/*.rb

  mvn clean package scala:run -Dlauncher=ruby-codegen &&
  (
    cd clients/ruby
    GEMFILE=$(gem build pandarus.gemspec | fgrep -i 'FILE:' | awk '{ print $2 }')
    echo "Gem file: $GEMFILE"
    gem install $GEMFILE  
  )

)