require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class AssignmentGroup < ModelBase
    attr_accessor :id, :name, :position, :group_weight, :assignments, :rules


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :position => {:external => "position", :container => false, :type => nil},
        :group_weight => {:external => "group_weight", :container => false, :type => nil},
        :assignments => {:external => "assignments", :container => false, :type => nil},
        :rules => {:external => "rules", :container => false, :type => nil}

      }
    end
  end
end

