require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class Collection < ModelBase
    attr_accessor :id, :name, :visibility, :followed_by_user, :followers_count, :items_count


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :visibility => {:external => "visibility", :container => false, :type => nil},
        :followed_by_user => {:external => "followed_by_user", :container => false, :type => nil},
        :followers_count => {:external => "followers_count", :container => false, :type => nil},
        :items_count => {:external => "items_count", :container => false, :type => nil}

      }
    end
  end
end

