require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class Day < ModelBase
    attr_accessor :date, :graders


    def self.attribute_map
      {
        :date => {:external => "date", :container => false, :type => "Date"},
        :graders => {:external => "graders", :container => false, :type => nil}

      }
    end
  end
end

