require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class Grader < ModelBase
    attr_accessor :id, :name, :assignments


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :assignments => {:external => "assignments", :container => false, :type => nil}

      }
    end
  end
end

