require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class GroupMembership < ModelBase
    attr_accessor :id, :group_id, :user_id, :workflow_state, :moderator


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :group_id => {:external => "group_id", :container => false, :type => nil},
        :user_id => {:external => "user_id", :container => false, :type => nil},
        :workflow_state => {:external => "workflow_state", :container => false, :type => nil},
        :moderator => {:external => "moderator", :container => false, :type => nil}

      }
    end
  end
end

