require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class GroupCategory < ModelBase
    attr_accessor :id, :name, :role, :self_signup, :context_type, :account_id, :group_limit, :progress


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :role => {:external => "role", :container => false, :type => nil},
        :self_signup => {:external => "self_signup", :container => false, :type => nil},
        :context_type => {:external => "context_type", :container => false, :type => nil},
        :account_id => {:external => "account_id", :container => false, :type => nil},
        :group_limit => {:external => "group_limit", :container => false, :type => nil},
        :progress => {:external => "progress", :container => false, :type => nil}

      }
    end
  end
end

