require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class OutcomeGroup < ModelBase
    attr_accessor :id, :url, :parent_outcome_group, :context_id, :context_type, :title, :description, :vendor_guid, :subgroups_url, :outcomes_url, :import_url, :can_edit


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :parent_outcome_group => {:external => "parent_outcome_group", :container => false, :type => nil},
        :context_id => {:external => "context_id", :container => false, :type => nil},
        :context_type => {:external => "context_type", :container => false, :type => nil},
        :title => {:external => "title", :container => false, :type => nil},
        :description => {:external => "description", :container => false, :type => nil},
        :vendor_guid => {:external => "vendor_guid", :container => false, :type => nil},
        :subgroups_url => {:external => "subgroups_url", :container => false, :type => nil},
        :outcomes_url => {:external => "outcomes_url", :container => false, :type => nil},
        :import_url => {:external => "import_url", :container => false, :type => nil},
        :can_edit => {:external => "can_edit", :container => false, :type => nil}

      }
    end
  end
end

