require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class Role < ModelBase
    attr_accessor :role, :base_role_type, :account, :workflow_state, :permissions


    def self.attribute_map
      {
        :role => {:external => "role", :container => false, :type => nil},
        :base_role_type => {:external => "base_role_type", :container => false, :type => nil},
        :account => {:external => "account", :container => false, :type => nil},
        :workflow_state => {:external => "workflow_state", :container => false, :type => nil},
        :permissions => {:external => "permissions", :container => false, :type => nil}

      }
    end
  end
end

