require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class Section < ModelBase
    attr_accessor :id, :name, :sis_section_id, :course_id, :start_at, :end_at, :nonxlist_course_id


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :sis_section_id => {:external => "sis_section_id", :container => false, :type => nil},
        :course_id => {:external => "course_id", :container => false, :type => nil},
        :start_at => {:external => "start_at", :container => false, :type => nil},
        :end_at => {:external => "end_at", :container => false, :type => nil},
        :nonxlist_course_id => {:external => "nonxlist_course_id", :container => false, :type => nil}

      }
    end
  end
end

