require "red_panda/model_base"

# This is an autogenerated file. See readme.md.
module RedPanda
  class SubmissionHistory < ModelBase
    attr_accessor :submission_id, :versions


    def self.attribute_map
      {
        :submission_id => {:external => "submission_id", :container => false, :type => nil},
        :versions => {:external => "versions", :container => false, :type => nil}

      }
    end
  end
end

