require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class AccountAuthorizationConfig < ModelBase
    attr_accessor :login_handle_name, :identifier_format, :auth_type, :id, :log_out_url, :log_in_url, :certificate_fingerprint, :change_password_url, :requested_authn_context, :auth_host, :auth_filter, :auth_over_tls, :auth_base, :auth_username, :auth_port, :position, :idp_entity_id, :login_attribute


    def self.attribute_map
      {
        :login_handle_name => {:external => "login_handle_name", :container => false, :type => "String"},
        :identifier_format => {:external => "identifier_format", :container => false, :type => "String"},
        :auth_type => {:external => "auth_type", :container => false, :type => "String"},
        :id => {:external => "id", :container => false, :type => "Integer"},
        :log_out_url => {:external => "log_out_url", :container => false, :type => "String"},
        :log_in_url => {:external => "log_in_url", :container => false, :type => "String"},
        :certificate_fingerprint => {:external => "certificate_fingerprint", :container => false, :type => "String"},
        :change_password_url => {:external => "change_password_url", :container => false, :type => "String"},
        :requested_authn_context => {:external => "requested_authn_context", :container => false, :type => "String"},
        :auth_host => {:external => "auth_host", :container => false, :type => "String"},
        :auth_filter => {:external => "auth_filter", :container => false, :type => "String"},
        :auth_over_tls => {:external => "auth_over_tls", :container => false, :type => "Integer"},
        :auth_base => {:external => "auth_base", :container => false, :type => "String"},
        :auth_username => {:external => "auth_username", :container => false, :type => "String"},
        :auth_port => {:external => "auth_port", :container => false, :type => "Integer"},
        :position => {:external => "position", :container => false, :type => "Integer"},
        :idp_entity_id => {:external => "idp_entity_id", :container => false, :type => "String"},
        :login_attribute => {:external => "login_attribute", :container => false, :type => "String"}

      }
    end
  end
end

