# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class AccountAuthorizationConfig < ModelBase
    include Virtus.model(finalize: false)

    attribute :login_handle_name, resolve_type("String")
    attribute :identifier_format, resolve_type("String")
    attribute :auth_type, resolve_type("String")
    attribute :id, resolve_type("Integer")
    attribute :log_out_url, resolve_type("String")
    attribute :log_in_url, resolve_type("String")
    attribute :certificate_fingerprint, resolve_type("String")
    attribute :change_password_url, resolve_type("String")
    attribute :requested_authn_context, resolve_type("String")
    attribute :auth_host, resolve_type("String")
    attribute :auth_filter, resolve_type("String")
    attribute :auth_over_tls, resolve_type("Integer")
    attribute :auth_base, resolve_type("String")
    attribute :auth_username, resolve_type("String")
    attribute :auth_port, resolve_type("Integer")
    attribute :position, resolve_type("Integer")
    attribute :idp_entity_id, resolve_type("String")
    attribute :login_attribute, resolve_type("String")
    attribute :unknown_user_url, resolve_type("String")
    
  end
end

