# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Admin < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :role, resolve_type("String")
    attribute :user, resolve_type("User")
    attribute :status, resolve_type("String")
    
  end
end

