require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Admin < ModelBase
    attr_accessor :id, :role, :user, :status


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :role => {:external => "role", :container => false, :type => "String"},
        :user => {:external => "user", :container => false, :type => "User"},
        :status => {:external => "status", :container => false, :type => "String"}

      }
    end
  end
end

