# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class AssignmentGroup < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :position, resolve_type("Integer")
    attribute :group_weight, resolve_type("Integer")
    attribute :assignments, resolve_type("Integer", collection: true)
    attribute :rules, resolve_type("GradingRules")
    
  end
end

