require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Assignment < ModelBase
    attr_accessor :id, :name, :description, :due_at, :lock_at, :unlock_at, :all_dates, :course_id, :html_url, :assignment_group_id, :allowed_extensions, :turnitin_enabled, :turnitin_settings, :grade_group_students_individually, :external_tool_tag_attributes, :peer_reviews, :automatic_peer_reviews, :peer_review_count, :peer_reviews_assign_at, :group_category_id, :needs_grading_count, :position, :muted, :points_possible, :submission_types, :grading_type, :grading_standard_id, :published, :unpublishable, :locked_for_user, :lock_info, :lock_explanation, :quiz_id, :anonymous_submissions, :discussion_topic, :freeze_on_copy, :frozen, :frozen_attributes, :submission, :use_rubric_for_grading, :rubric_settings, :rubric


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :name => {:external => "name", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"},
        :due_at => {:external => "due_at", :container => false, :type => "DateTime"},
        :lock_at => {:external => "lock_at", :container => false, :type => "DateTime"},
        :unlock_at => {:external => "unlock_at", :container => false, :type => "DateTime"},
        :all_dates => {:external => "all_dates", :container => true, :type => "AssignmentDate"},
        :course_id => {:external => "course_id", :container => false, :type => "Integer"},
        :html_url => {:external => "html_url", :container => false, :type => "String"},
        :assignment_group_id => {:external => "assignment_group_id", :container => false, :type => "Integer"},
        :allowed_extensions => {:external => "allowed_extensions", :container => true, :type => "String"},
        :turnitin_enabled => {:external => "turnitin_enabled", :container => false, :type => nil},
        :turnitin_settings => {:external => "turnitin_settings", :container => false, :type => "TurnitinSettings"},
        :grade_group_students_individually => {:external => "grade_group_students_individually", :container => false, :type => nil},
        :external_tool_tag_attributes => {:external => "external_tool_tag_attributes", :container => false, :type => "ExternalToolTagAttributes"},
        :peer_reviews => {:external => "peer_reviews", :container => false, :type => nil},
        :automatic_peer_reviews => {:external => "automatic_peer_reviews", :container => false, :type => nil},
        :peer_review_count => {:external => "peer_review_count", :container => false, :type => "Integer"},
        :peer_reviews_assign_at => {:external => "peer_reviews_assign_at", :container => false, :type => "DateTime"},
        :group_category_id => {:external => "group_category_id", :container => false, :type => "Integer"},
        :needs_grading_count => {:external => "needs_grading_count", :container => false, :type => "Integer"},
        :position => {:external => "position", :container => false, :type => "Integer"},
        :muted => {:external => "muted", :container => false, :type => "Integer"},
        :points_possible => {:external => "points_possible", :container => false, :type => "Integer"},
        :submission_types => {:external => "submission_types", :container => true, :type => "String"},
        :grading_type => {:external => "grading_type", :container => false, :type => "String"},
        :grading_standard_id => {:external => "grading_standard_id", :container => false, :type => "Integer"},
        :published => {:external => "published", :container => false, :type => nil},
        :unpublishable => {:external => "unpublishable", :container => false, :type => nil},
        :locked_for_user => {:external => "locked_for_user", :container => false, :type => nil},
        :lock_info => {:external => "lock_info", :container => false, :type => "LockInfo"},
        :lock_explanation => {:external => "lock_explanation", :container => false, :type => "String"},
        :quiz_id => {:external => "quiz_id", :container => false, :type => "Integer"},
        :anonymous_submissions => {:external => "anonymous_submissions", :container => false, :type => nil},
        :discussion_topic => {:external => "discussion_topic", :container => false, :type => "DiscussionTopic"},
        :freeze_on_copy => {:external => "freeze_on_copy", :container => false, :type => nil},
        :frozen => {:external => "frozen", :container => false, :type => nil},
        :frozen_attributes => {:external => "frozen_attributes", :container => true, :type => "String"},
        :submission => {:external => "submission", :container => false, :type => "Submission"},
        :use_rubric_for_grading => {:external => "use_rubric_for_grading", :container => false, :type => nil},
        :rubric_settings => {:external => "rubric_settings", :container => false, :type => "String"},
        :rubric => {:external => "rubric", :container => false, :type => "RubricCriteria"}

      }
    end
  end
end

