require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class AssignmentOverride < ModelBase
    attr_accessor :id, :assignment_id, :student_ids, :group_id, :course_section_id, :title, :due_at, :all_day, :all_day_date, :unlock_at, :lock_at


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :assignment_id => {:external => "assignment_id", :container => false, :type => "Integer"},
        :student_ids => {:external => "student_ids", :container => true, :type => "Integer"},
        :group_id => {:external => "group_id", :container => false, :type => "Integer"},
        :course_section_id => {:external => "course_section_id", :container => false, :type => "Integer"},
        :title => {:external => "title", :container => false, :type => "String"},
        :due_at => {:external => "due_at", :container => false, :type => "DateTime"},
        :all_day => {:external => "all_day", :container => false, :type => "Integer"},
        :all_day_date => {:external => "all_day_date", :container => false, :type => "DateTime"},
        :unlock_at => {:external => "unlock_at", :container => false, :type => "DateTime"},
        :lock_at => {:external => "lock_at", :container => false, :type => "DateTime"}

      }
    end
  end
end

