require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Avatar < ModelBase
    attr_accessor :type, :url, :token, :display_name, :id, :content_type, :filename, :size


    def self.attribute_map
      {
        :type => {:external => "type", :container => false, :type => "String"},
        :url => {:external => "url", :container => false, :type => "String"},
        :token => {:external => "token", :container => false, :type => "String"},
        :display_name => {:external => "display_name", :container => false, :type => "String"},
        :id => {:external => "id", :container => false, :type => "Integer"},
        :content_type => {:external => "content-type", :container => false, :type => "String"},
        :filename => {:external => "filename", :container => false, :type => "String"},
        :size => {:external => "size", :container => false, :type => "Integer"}

      }
    end
  end
end

