# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Avatar < ModelBase
    include Virtus.model(finalize: false)

    attribute :type, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :token, resolve_type("String")
    attribute :display_name, resolve_type("String")
    attribute :id, resolve_type("Integer")
    attribute :content_type, resolve_type("String")
    attribute :filename, resolve_type("String")
    attribute :size, resolve_type("Integer")
    
  end
end

