# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class BlueprintMigration < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type(nil)
    attribute :template_id, resolve_type(nil)
    attribute :subscription_id, resolve_type(nil)
    attribute :user_id, resolve_type(nil)
    attribute :workflow_state, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :exports_started_at, resolve_type("DateTime")
    attribute :imports_queued_at, resolve_type("DateTime")
    attribute :imports_completed_at, resolve_type("DateTime")
    attribute :comment, resolve_type("String")
    
  end
end

