# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Bookmark < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :position, resolve_type("Integer")
    attribute :data, resolve_type("Object")
    
  end
end

