# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CalendarEvent < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :title, resolve_type("String")
    attribute :start_at, resolve_type("DateTime")
    attribute :end_at, resolve_type("DateTime")
    attribute :description, resolve_type("String")
    attribute :location_name, resolve_type("String")
    attribute :location_address, resolve_type("String")
    attribute :context_code, resolve_type("String")
    attribute :effective_context_code, resolve_type("String")
    attribute :workflow_state, resolve_type("String")
    attribute :hidden, resolve_type(nil)
    attribute :parent_event_id, resolve_type("Integer")
    attribute :child_events_count, resolve_type("Integer")
    attribute :child_events, resolve_type("Integer", collection: true)
    attribute :url, resolve_type("String")
    attribute :html_url, resolve_type("String")
    attribute :all_day_date, resolve_type("DateTime")
    attribute :all_day, resolve_type(nil)
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :appointment_group_id, resolve_type("Integer")
    attribute :appointment_group_url, resolve_type("String")
    attribute :own_reservation, resolve_type(nil)
    attribute :reserve_url, resolve_type("String")
    attribute :reserved, resolve_type(nil)
    attribute :participants_per_appointment, resolve_type("Integer")
    attribute :available_slots, resolve_type("Integer")
    attribute :user, resolve_type("String")
    attribute :group, resolve_type("String")
    
  end
end

