require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CalendarEvent < ModelBase
    attr_accessor :id, :title, :start_at, :end_at, :description, :location_name, :location_address, :context_code, :effective_context_code, :workflow_state, :hidden, :parent_event_id, :child_events_count, :child_events, :url, :html_url, :all_day_date, :all_day, :created_at, :updated_at, :appointment_group_id, :appointment_group_url, :own_reservation, :reserve_url, :reserved, :participants_per_appointment, :available_slots, :user, :group


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :title => {:external => "title", :container => false, :type => "String"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :end_at => {:external => "end_at", :container => false, :type => "DateTime"},
        :description => {:external => "description", :container => false, :type => "String"},
        :location_name => {:external => "location_name", :container => false, :type => "String"},
        :location_address => {:external => "location_address", :container => false, :type => "String"},
        :context_code => {:external => "context_code", :container => false, :type => "String"},
        :effective_context_code => {:external => "effective_context_code", :container => false, :type => "String"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :hidden => {:external => "hidden", :container => false, :type => nil},
        :parent_event_id => {:external => "parent_event_id", :container => false, :type => "Integer"},
        :child_events_count => {:external => "child_events_count", :container => false, :type => "Integer"},
        :child_events => {:external => "child_events", :container => true, :type => "Integer"},
        :url => {:external => "url", :container => false, :type => "String"},
        :html_url => {:external => "html_url", :container => false, :type => "String"},
        :all_day_date => {:external => "all_day_date", :container => false, :type => "DateTime"},
        :all_day => {:external => "all_day", :container => false, :type => nil},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"},
        :appointment_group_id => {:external => "appointment_group_id", :container => false, :type => "Integer"},
        :appointment_group_url => {:external => "appointment_group_url", :container => false, :type => "String"},
        :own_reservation => {:external => "own_reservation", :container => false, :type => nil},
        :reserve_url => {:external => "reserve_url", :container => false, :type => "String"},
        :reserved => {:external => "reserved", :container => false, :type => nil},
        :participants_per_appointment => {:external => "participants_per_appointment", :container => false, :type => "Integer"},
        :available_slots => {:external => "available_slots", :container => false, :type => "Integer"},
        :user => {:external => "user", :container => false, :type => "String"},
        :group => {:external => "group", :container => false, :type => "String"}

      }
    end
  end
end

