require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CalendarLink < ModelBase
    attr_accessor :ics


    def self.attribute_map
      {
        :ics => {:external => "ics", :container => false, :type => "String"}

      }
    end
  end
end

