# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ChangeRecord < ModelBase
    include Virtus.model(finalize: false)

    attribute :asset_id, resolve_type(nil)
    attribute :asset_type, resolve_type("String")
    attribute :asset_name, resolve_type("String")
    attribute :change_type, resolve_type("String")
    attribute :html_url, resolve_type("String")
    attribute :locked, resolve_type(nil)
    attribute :exceptions, resolve_type("Object", collection: true)
    
  end
end

