# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Collaboration < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :collaboration_type, resolve_type("String")
    attribute :document_id, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    attribute :context_id, resolve_type("Integer")
    attribute :context_type, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :description, resolve_type("String")
    attribute :title, resolve_type("String")
    attribute :type, resolve_type("String")
    attribute :update_url, resolve_type("String")
    attribute :user_name, resolve_type("String")
    
  end
end

