# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Collaborator < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :type, resolve_type("String")
    attribute :name, resolve_type("String")
    
  end
end

