require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CollectionItem < ModelBase
    attr_accessor :id, :collection_id, :item_type, :link_url, :post_count, :upvote_count, :upvoted_by_user, :root_item_id, :image_url, :image_pending, :title, :description, :user_comment, :html_preview, :url, :created_at, :user


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :collection_id => {:external => "collection_id", :container => false, :type => nil},
        :item_type => {:external => "item_type", :container => false, :type => nil},
        :link_url => {:external => "link_url", :container => false, :type => nil},
        :post_count => {:external => "post_count", :container => false, :type => nil},
        :upvote_count => {:external => "upvote_count", :container => false, :type => nil},
        :upvoted_by_user => {:external => "upvoted_by_user", :container => false, :type => nil},
        :root_item_id => {:external => "root_item_id", :container => false, :type => nil},
        :image_url => {:external => "image_url", :container => false, :type => nil},
        :image_pending => {:external => "image_pending", :container => false, :type => nil},
        :title => {:external => "title", :container => false, :type => nil},
        :description => {:external => "description", :container => false, :type => nil},
        :user_comment => {:external => "user_comment", :container => false, :type => nil},
        :html_preview => {:external => "html_preview", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :created_at => {:external => "created_at", :container => false, :type => "Date"},
        :user => {:external => "user", :container => false, :type => nil}

      }
    end
  end
end

