# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ColumnDatum < ModelBase
    include Virtus.model(finalize: false)

    attribute :content, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    
  end
end

