require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ColumnDatum < ModelBase
    attr_accessor :content, :user_id


    def self.attribute_map
      {
        :content => {:external => "content", :container => false, :type => nil},
        :user_id => {:external => "user_id", :container => false, :type => nil}

      }
    end
  end
end

