require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CommMessage < ModelBase
    attr_accessor :id, :created_at, :sent_at, :workflow_state, :from, :to, :reply_to, :subject, :body, :html_body


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :sent_at => {:external => "sent_at", :container => false, :type => "DateTime"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :from => {:external => "from", :container => false, :type => "String"},
        :to => {:external => "to", :container => false, :type => "String"},
        :reply_to => {:external => "reply_to", :container => false, :type => "String"},
        :subject => {:external => "subject", :container => false, :type => "String"},
        :body => {:external => "body", :container => false, :type => "String"},
        :html_body => {:external => "html_body", :container => false, :type => "String"}

      }
    end
  end
end

