require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CommunicationChannel < ModelBase
    attr_accessor :id, :address, :type, :position, :user_id, :workflow_state


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :address => {:external => "address", :container => false, :type => nil},
        :type => {:external => "type", :container => false, :type => nil},
        :position => {:external => "position", :container => false, :type => nil},
        :user_id => {:external => "user_id", :container => false, :type => nil},
        :workflow_state => {:external => "workflow_state", :container => false, :type => nil}

      }
    end
  end
end

