# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CommunicationChannel < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :address, resolve_type("String")
    attribute :type, resolve_type("String")
    attribute :position, resolve_type("Integer")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    
  end
end

