# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CompletionRequirement < ModelBase
    include Virtus.model(finalize: false)

    attribute :type, resolve_type("String")
    attribute :min_score, resolve_type("Integer")
    attribute :completed, resolve_type(nil)
    
  end
end

