require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CompletionRequirement < ModelBase
    attr_accessor :type, :min_score, :completed


    def self.attribute_map
      {
        :type => {:external => "type", :container => false, :type => "String"},
        :min_score => {:external => "min_score", :container => false, :type => "Integer"},
        :completed => {:external => "completed", :container => false, :type => nil}

      }
    end
  end
end

