require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ConferenceRecording < ModelBase
    attr_accessor :duration_minutes, :title, :updated_at, :created_at, :playback_url


    def self.attribute_map
      {
        :duration_minutes => {:external => "duration_minutes", :container => false, :type => "Integer"},
        :title => {:external => "title", :container => false, :type => "String"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :playback_url => {:external => "playback_url", :container => false, :type => "String"}

      }
    end
  end
end

