require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ContentMigration < ModelBase
    attr_accessor :id, :migration_type, :migration_type_title, :migration_issues_url, :attachment, :progress_url, :user_id, :workflow_state, :started_at, :finished_at, :pre_attachment


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :migration_type => {:external => "migration_type", :container => false, :type => "String"},
        :migration_type_title => {:external => "migration_type_title", :container => false, :type => "String"},
        :migration_issues_url => {:external => "migration_issues_url", :container => false, :type => "String"},
        :attachment => {:external => "attachment", :container => false, :type => "String"},
        :progress_url => {:external => "progress_url", :container => false, :type => "String"},
        :user_id => {:external => "user_id", :container => false, :type => "Integer"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :started_at => {:external => "started_at", :container => false, :type => "DateTime"},
        :finished_at => {:external => "finished_at", :container => false, :type => "DateTime"},
        :pre_attachment => {:external => "pre_attachment", :container => false, :type => "String"}

      }
    end
  end
end

