# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ContentMigration < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :migration_type, resolve_type("String")
    attribute :migration_type_title, resolve_type("String")
    attribute :migration_issues_url, resolve_type("String")
    attribute :attachment, resolve_type("String")
    attribute :progress_url, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :started_at, resolve_type("DateTime")
    attribute :finished_at, resolve_type("DateTime")
    attribute :pre_attachment, resolve_type("String")
    
  end
end

