require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Conversation < ModelBase
    attr_accessor :id, :subject, :workflow_state, :last_message, :start_at, :message_count, :subscribed, :private, :starred, :properties, :audience, :audience_contexts, :avatar_url, :participants, :visible, :context_name


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :subject => {:external => "subject", :container => false, :type => "String"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :last_message => {:external => "last_message", :container => false, :type => "String"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :message_count => {:external => "message_count", :container => false, :type => "Integer"},
        :subscribed => {:external => "subscribed", :container => false, :type => nil},
        :private => {:external => "private", :container => false, :type => nil},
        :starred => {:external => "starred", :container => false, :type => nil},
        :properties => {:external => "properties", :container => false, :type => "[string]"},
        :audience => {:external => "audience", :container => false, :type => "[integer]"},
        :audience_contexts => {:external => "audience_contexts", :container => false, :type => "[string]"},
        :avatar_url => {:external => "avatar_url", :container => false, :type => "String"},
        :participants => {:external => "participants", :container => false, :type => "[string]"},
        :visible => {:external => "visible", :container => false, :type => nil},
        :context_name => {:external => "context_name", :container => false, :type => "String"}

      }
    end
  end
end

