# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ConversationParticipant < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type(nil)
    attribute :name, resolve_type("String")
    attribute :full_name, resolve_type("String")
    attribute :avatar_url, resolve_type("String")
    
  end
end

