# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Course < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :sis_course_id, resolve_type("String")
    attribute :integration_id, resolve_type("String")
    attribute :name, resolve_type("String")
    attribute :course_code, resolve_type("String")
    attribute :workflow_state, resolve_type("String")
    attribute :account_id, resolve_type("Integer")
    attribute :root_account_id, resolve_type("Integer")
    attribute :enrollment_term_id, resolve_type("Integer")
    attribute :start_at, resolve_type("DateTime")
    attribute :end_at, resolve_type("DateTime")
    attribute :enrollments, resolve_type("Enrollment", collection: true)
    attribute :total_students, resolve_type("Integer")
    attribute :calendar, resolve_type("CalendarLink")
    attribute :default_view, resolve_type("String")
    attribute :syllabus_body, resolve_type("String")
    attribute :needs_grading_count, resolve_type("Integer")
    attribute :term, resolve_type("Term")
    attribute :course_progress, resolve_type("CourseProgress")
    attribute :apply_assignment_group_weights, resolve_type(nil)
    attribute :permissions, resolve_type("Map")
    attribute :is_public, resolve_type(nil)
    attribute :is_public_to_auth_users, resolve_type(nil)
    attribute :public_syllabus, resolve_type(nil)
    attribute :public_description, resolve_type("String")
    attribute :storage_quota_mb, resolve_type("Integer")
    attribute :storage_quota_used_mb, resolve_type("Float")
    attribute :hide_final_grades, resolve_type(nil)
    attribute :license, resolve_type("String")
    attribute :allow_student_assignment_edits, resolve_type(nil)
    attribute :allow_wiki_comments, resolve_type(nil)
    attribute :allow_student_forum_attachments, resolve_type(nil)
    attribute :open_enrollment, resolve_type(nil)
    attribute :self_enrollment, resolve_type(nil)
    attribute :restrict_enrollments_to_course_dates, resolve_type(nil)
    attribute :course_format, resolve_type("String")
    
  end
end

