require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CourseEvent < ModelBase
    attr_accessor :id, :created_at, :event_type, :event_data, :links


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :created_at => {:external => "created_at", :container => false, :type => nil},
        :event_type => {:external => "event_type", :container => false, :type => nil},
        :event_data => {:external => "event_data", :container => false, :type => nil},
        :links => {:external => "links", :container => false, :type => nil}

      }
    end
  end
end

