require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CourseEventLink < ModelBase
    attr_accessor :course, :user, :page_view


    def self.attribute_map
      {
        :course => {:external => "course", :container => false, :type => "Integer"},
        :user => {:external => "user", :container => false, :type => "Integer"},
        :page_view => {:external => "page_view", :container => false, :type => "String"}

      }
    end
  end
end

