require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CourseEventLink < ModelBase
    attr_accessor :course, :user, :page_view, :copied_from, :copied_to, :sis_batch


    def self.attribute_map
      {
        :course => {:external => "course", :container => false, :type => "Integer"},
        :user => {:external => "user", :container => false, :type => "Integer"},
        :page_view => {:external => "page_view", :container => false, :type => "String"},
        :copied_from => {:external => "copied_from", :container => false, :type => "Integer"},
        :copied_to => {:external => "copied_to", :container => false, :type => "Integer"},
        :sis_batch => {:external => "sis_batch", :container => false, :type => "Integer"}

      }
    end
  end
end

