require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class CourseProgress < ModelBase
    attr_accessor :requirement_count, :requirement_completed_count, :next_requirement_url, :completed_at


    def self.attribute_map
      {
        :requirement_count => {:external => "requirement_count", :container => false, :type => "Integer"},
        :requirement_completed_count => {:external => "requirement_completed_count", :container => false, :type => "Integer"},
        :next_requirement_url => {:external => "next_requirement_url", :container => false, :type => "String"},
        :completed_at => {:external => "completed_at", :container => false, :type => "DateTime"}

      }
    end
  end
end

