# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CourseNickname < ModelBase
    include Virtus.model(finalize: false)

    attribute :course_id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :nickname, resolve_type("String")
    
  end
end

