# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CourseEvent < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :event_type, resolve_type("String")
    attribute :event_data, resolve_type("String")
    attribute :event_source, resolve_type("String")
    attribute :links, resolve_type("CourseEventLink")
    
  end
end

