# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CourseEventLink < ModelBase
    include Virtus.model(finalize: false)

    attribute :course, resolve_type("Integer")
    attribute :user, resolve_type("Integer")
    attribute :page_view, resolve_type("String")
    attribute :copied_from, resolve_type("Integer")
    attribute :copied_to, resolve_type("Integer")
    attribute :sis_batch, resolve_type("Integer")
    
  end
end

