# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class CustomColumn < ModelBase
    include Virtus.model(finalize: false)

    attribute :title, resolve_type("String")
    attribute :position, resolve_type("Integer")
    attribute :hidden, resolve_type(nil)
    
  end
end

