# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Day < ModelBase
    include Virtus.model(finalize: false)

    attribute :date, resolve_type("DateTime")
    attribute :graders, resolve_type("Integer")
    
  end
end

