require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Day < ModelBase
    attr_accessor :date, :graders


    def self.attribute_map
      {
        :date => {:external => "date", :container => false, :type => "DateTime"},
        :graders => {:external => "graders", :container => false, :type => "Integer"}

      }
    end
  end
end

