# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class DiscoveryUrl < ModelBase
    include Virtus.model(finalize: false)

    attribute :discovery_url, resolve_type("String")
    
  end
end

