# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class DiscussionTopic < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :title, resolve_type("String")
    attribute :message, resolve_type("String")
    attribute :html_url, resolve_type("String")
    attribute :posted_at, resolve_type("DateTime")
    attribute :last_reply_at, resolve_type("DateTime")
    attribute :require_initial_post, resolve_type(nil)
    attribute :user_can_see_posts, resolve_type(nil)
    attribute :discussion_subentry_count, resolve_type("Integer")
    attribute :read_state, resolve_type("String")
    attribute :unread_count, resolve_type("Integer")
    attribute :subscribed, resolve_type(nil)
    attribute :subscription_hold, resolve_type("String")
    attribute :assignment_id, resolve_type("Integer")
    attribute :delayed_post_at, resolve_type("DateTime")
    attribute :published, resolve_type(nil)
    attribute :lock_at, resolve_type("DateTime")
    attribute :locked, resolve_type(nil)
    attribute :pinned, resolve_type(nil)
    attribute :locked_for_user, resolve_type(nil)
    attribute :lock_info, resolve_type("LockInfo")
    attribute :lock_explanation, resolve_type("String")
    attribute :user_name, resolve_type("String")
    attribute :topic_children, resolve_type("Integer", collection: true)
    attribute :root_topic_id, resolve_type("Integer")
    attribute :podcast_url, resolve_type("String")
    attribute :discussion_type, resolve_type("String")
    attribute :group_category_id, resolve_type("Integer")
    attribute :attachments, resolve_type("FileAttachment", collection: true)
    attribute :permissions, resolve_type("Map")
    
  end
end

