require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class EnrollmentTerm < ModelBase
    attr_accessor :id, :sis_term_id, :name, :start_at, :end_at, :workflow_state


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :sis_term_id => {:external => "sis_term_id", :container => false, :type => "String"},
        :name => {:external => "name", :container => false, :type => "String"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :end_at => {:external => "end_at", :container => false, :type => "DateTime"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"}

      }
    end
  end
end

