require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ExternalFeed < ModelBase
    attr_accessor :id, :display_name, :url, :header_match, :created_at, :verbosity


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :display_name => {:external => "display_name", :container => false, :type => "String"},
        :url => {:external => "url", :container => false, :type => "String"},
        :header_match => {:external => "header_match", :container => false, :type => "String"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :verbosity => {:external => "verbosity", :container => false, :type => "String"}

      }
    end
  end
end

