# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ExternalToolTagAttributes < ModelBase
    include Virtus.model(finalize: false)

    attribute :url, resolve_type("String")
    attribute :new_tab, resolve_type(nil)
    attribute :resource_link_id, resolve_type("String")
    
  end
end

