require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ExternalToolTagAttributes < ModelBase
    attr_accessor :url, :new_tab, :resource_link_id


    def self.attribute_map
      {
        :url => {:external => "url", :container => false, :type => "String"},
        :new_tab => {:external => "new_tab", :container => false, :type => nil},
        :resource_link_id => {:external => "resource_link_id", :container => false, :type => "String"}

      }
    end
  end
end

