require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Favorite < ModelBase
    attr_accessor :context_id, :context_type


    def self.attribute_map
      {
        :context_id => {:external => "context_id", :container => false, :type => nil},
        :context_type => {:external => "context_type", :container => false, :type => nil}

      }
    end
  end
end

