# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Favorite < ModelBase
    include Virtus.model(finalize: false)

    attribute :context_id, resolve_type("Integer")
    attribute :context_type, resolve_type("String")
    
  end
end

