require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Feature < ModelBase
    attr_accessor :name, :display_name, :applies_to, :enable_at, :feature_flag, :root_opt_in, :beta, :development, :release_notes_url


    def self.attribute_map
      {
        :name => {:external => "name", :container => false, :type => "String"},
        :display_name => {:external => "display_name", :container => false, :type => "String"},
        :applies_to => {:external => "applies_to", :container => false, :type => "String"},
        :enable_at => {:external => "enable_at", :container => false, :type => "DateTime"},
        :feature_flag => {:external => "feature_flag", :container => false, :type => "FeatureFlag"},
        :root_opt_in => {:external => "root_opt_in", :container => false, :type => nil},
        :beta => {:external => "beta", :container => false, :type => nil},
        :development => {:external => "development", :container => false, :type => nil},
        :release_notes_url => {:external => "release_notes_url", :container => false, :type => "String"}

      }
    end
  end
end

