# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class FeatureFlag < ModelBase
    include Virtus.model(finalize: false)

    attribute :context_type, resolve_type("String")
    attribute :context_id, resolve_type("Integer")
    attribute :feature, resolve_type("String")
    attribute :state, resolve_type("String")
    attribute :locked, resolve_type(nil)
    attribute :locking_account_id, resolve_type("Integer")
    
  end
end

