# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class File < ModelBase
    include Virtus.model(finalize: false)

    attribute :size, resolve_type("Integer")
    attribute :content_type, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :id, resolve_type("Integer")
    attribute :display_name, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :unlock_at, resolve_type("DateTime")
    attribute :locked, resolve_type(nil)
    attribute :hidden, resolve_type(nil)
    attribute :lock_at, resolve_type("DateTime")
    attribute :locked_for_user, resolve_type(nil)
    attribute :lock_info, resolve_type("LockInfo")
    attribute :lock_explanation, resolve_type("String")
    attribute :hidden_for_user, resolve_type(nil)
    attribute :thumbnail_url, resolve_type("String")
    attribute :preview_url, resolve_type("String")
    
  end
end

