require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class File < ModelBase
    attr_accessor :size, :content_type, :url, :id, :display_name, :created_at, :updated_at, :unlock_at, :locked, :hidden, :lock_at, :locked_for_user, :lock_info, :lock_explanation, :hidden_for_user, :thumbnail_url


    def self.attribute_map
      {
        :size => {:external => "size", :container => false, :type => nil},
        :content_type => {:external => "content-type", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :id => {:external => "id", :container => false, :type => nil},
        :display_name => {:external => "display_name", :container => false, :type => nil},
        :created_at => {:external => "created_at", :container => false, :type => "Date"},
        :updated_at => {:external => "updated_at", :container => false, :type => "Date"},
        :unlock_at => {:external => "unlock_at", :container => false, :type => nil},
        :locked => {:external => "locked", :container => false, :type => nil},
        :hidden => {:external => "hidden", :container => false, :type => nil},
        :lock_at => {:external => "lock_at", :container => false, :type => nil},
        :locked_for_user => {:external => "locked_for_user", :container => false, :type => nil},
        :lock_info => {:external => "lock_info", :container => false, :type => nil},
        :lock_explanation => {:external => "lock_explanation", :container => false, :type => nil},
        :hidden_for_user => {:external => "hidden_for_user", :container => false, :type => nil},
        :thumbnail_url => {:external => "thumbnail_url", :container => false, :type => nil}

      }
    end
  end
end

