# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class FileAttachment < ModelBase
    include Virtus.model(finalize: false)

    attribute :content_type, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :filename, resolve_type("String")
    attribute :display_name, resolve_type("String")
    
  end
end

