require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class GradingRules < ModelBase
    attr_accessor :drop_lowest, :drop_highest, :never_drop


    def self.attribute_map
      {
        :drop_lowest => {:external => "drop_lowest", :container => false, :type => "Integer"},
        :drop_highest => {:external => "drop_highest", :container => false, :type => "Integer"},
        :never_drop => {:external => "never_drop", :container => true, :type => "Integer"}

      }
    end
  end
end

