# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class GradingRules < ModelBase
    include Virtus.model(finalize: false)

    attribute :drop_lowest, resolve_type("Integer")
    attribute :drop_highest, resolve_type("Integer")
    attribute :never_drop, resolve_type("Integer", collection: true)
    
  end
end

