require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class GradingSchemeEntry < ModelBase
    attr_accessor :name, :value


    def self.attribute_map
      {
        :name => {:external => "name", :container => false, :type => "String"},
        :value => {:external => "value", :container => false, :type => "Integer"}

      }
    end
  end
end

