require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class GradeChangeEventLinks < ModelBase
    attr_accessor :assignment, :course, :student, :grader, :page_view


    def self.attribute_map
      {
        :assignment => {:external => "assignment", :container => false, :type => "Integer"},
        :course => {:external => "course", :container => false, :type => "Integer"},
        :student => {:external => "student", :container => false, :type => "Integer"},
        :grader => {:external => "grader", :container => false, :type => "Integer"},
        :page_view => {:external => "page_view", :container => false, :type => "String"}

      }
    end
  end
end

