# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Grade < ModelBase
    include Virtus.model(finalize: false)

    attribute :html_url, resolve_type("String")
    attribute :current_grade, resolve_type("String")
    attribute :final_grade, resolve_type("String")
    attribute :current_score, resolve_type("String")
    attribute :final_score, resolve_type("String")
    
  end
end

