# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class GradingStandard < ModelBase
    include Virtus.model(finalize: false)

    attribute :title, resolve_type("String")
    attribute :id, resolve_type("Integer")
    attribute :context_type, resolve_type("String")
    attribute :context_id, resolve_type("Integer")
    attribute :grading_scheme, resolve_type("GradingSchemeEntry", collection: true)
    
  end
end

