require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class GradingStandard < ModelBase
    attr_accessor :title, :id, :context_type, :context_id, :grading_scheme


    def self.attribute_map
      {
        :title => {:external => "title", :container => false, :type => "String"},
        :id => {:external => "id", :container => false, :type => "Integer"},
        :context_type => {:external => "context_type", :container => false, :type => "String"},
        :context_id => {:external => "context_id", :container => false, :type => "Integer"},
        :grading_scheme => {:external => "grading_scheme", :container => true, :type => "GradingSchemeEntry"}

      }
    end
  end
end

