# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class GradingSchemeEntry < ModelBase
    include Virtus.model(finalize: false)

    attribute :name, resolve_type("String")
    attribute :value, resolve_type("Integer")
    
  end
end

