# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class GroupMembership < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :group_id, resolve_type("Integer")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :moderator, resolve_type(nil)
    attribute :just_created, resolve_type(nil)
    attribute :sis_import_id, resolve_type("Integer")
    
  end
end

