require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class GroupMembership < ModelBase
    attr_accessor :id, :group_id, :user_id, :workflow_state, :moderator, :just_created


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :group_id => {:external => "group_id", :container => false, :type => "Integer"},
        :user_id => {:external => "user_id", :container => false, :type => "Integer"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :moderator => {:external => "moderator", :container => false, :type => nil},
        :just_created => {:external => "just_created", :container => false, :type => nil}

      }
    end
  end
end

