# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class GroupCategory < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :role, resolve_type("String")
    attribute :self_signup, resolve_type("String")
    attribute :auto_leader, resolve_type("String")
    attribute :context_type, resolve_type("String")
    attribute :account_id, resolve_type("Integer")
    attribute :group_limit, resolve_type("Integer")
    attribute :progress, resolve_type("Progress")
    
  end
end

