require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Group < ModelBase
    attr_accessor :id, :name, :description, :is_public, :followed_by_user, :join_level, :members_count, :avatar_url, :context_type, :course_id, :role, :group_category_id, :storage_quota_mb, :permissions


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :name => {:external => "name", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"},
        :is_public => {:external => "is_public", :container => false, :type => nil},
        :followed_by_user => {:external => "followed_by_user", :container => false, :type => nil},
        :join_level => {:external => "join_level", :container => false, :type => "String"},
        :members_count => {:external => "members_count", :container => false, :type => "Integer"},
        :avatar_url => {:external => "avatar_url", :container => false, :type => "String"},
        :context_type => {:external => "context_type", :container => false, :type => "String"},
        :course_id => {:external => "course_id", :container => false, :type => "Integer"},
        :role => {:external => "role", :container => false, :type => "String"},
        :group_category_id => {:external => "group_category_id", :container => false, :type => "Integer"},
        :storage_quota_mb => {:external => "storage_quota_mb", :container => false, :type => "Integer"},
        :permissions => {:external => "permissions", :container => false, :type => "Map"}

      }
    end
  end
end

