# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Group < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :description, resolve_type("String")
    attribute :is_public, resolve_type(nil)
    attribute :followed_by_user, resolve_type(nil)
    attribute :join_level, resolve_type("String")
    attribute :members_count, resolve_type("Integer")
    attribute :avatar_url, resolve_type("String")
    attribute :context_type, resolve_type("String")
    attribute :course_id, resolve_type("Integer")
    attribute :role, resolve_type("String")
    attribute :group_category_id, resolve_type("Integer")
    attribute :sis_group_id, resolve_type("String")
    attribute :sis_import_id, resolve_type("Integer")
    attribute :storage_quota_mb, resolve_type("Integer")
    attribute :permissions, resolve_type("Map")
    
  end
end

