# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class JWT < ModelBase
    include Virtus.model(finalize: false)

    attribute :token, resolve_type("String")
    
  end
end

