# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class License < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("String")
    attribute :name, resolve_type("String")
    attribute :url, resolve_type("String")
    
  end
end

