# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class LockInfo < ModelBase
    include Virtus.model(finalize: false)

    attribute :asset_string, resolve_type("String")
    attribute :unlock_at, resolve_type("DateTime")
    attribute :lock_at, resolve_type("DateTime")
    attribute :context_module, resolve_type("String")
    attribute :manually_locked, resolve_type(nil)
    
  end
end

