require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class LockInfo < ModelBase
    attr_accessor :asset_string, :unlock_at, :lock_at, :context_module, :manually_locked


    def self.attribute_map
      {
        :asset_string => {:external => "asset_string", :container => false, :type => "String"},
        :unlock_at => {:external => "unlock_at", :container => false, :type => "DateTime"},
        :lock_at => {:external => "lock_at", :container => false, :type => "DateTime"},
        :context_module => {:external => "context_module", :container => false, :type => "String"},
        :manually_locked => {:external => "manually_locked", :container => false, :type => nil}

      }
    end
  end
end

