# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class LtiAssignment < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :description, resolve_type("String")
    attribute :points_possible, resolve_type("Integer")
    attribute :due_at, resolve_type("DateTime")
    attribute :lti_id, resolve_type("String")
    
  end
end

