require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class MigrationIssue < ModelBase
    attr_accessor :id, :content_migration_url, :description, :workflow_state, :fix_issue_html_url, :issue_type, :error_report_html_url, :error_message, :created_at, :updated_at


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :content_migration_url => {:external => "content_migration_url", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :fix_issue_html_url => {:external => "fix_issue_html_url", :container => false, :type => "String"},
        :issue_type => {:external => "issue_type", :container => false, :type => "String"},
        :error_report_html_url => {:external => "error_report_html_url", :container => false, :type => "String"},
        :error_message => {:external => "error_message", :container => false, :type => "String"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"}

      }
    end
  end
end

