require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Migrator < ModelBase
    attr_accessor :type, :requires_file_upload, :name, :required_settings


    def self.attribute_map
      {
        :type => {:external => "type", :container => false, :type => "String"},
        :requires_file_upload => {:external => "requires_file_upload", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => "String"},
        :required_settings => {:external => "required_settings", :container => true, :type => "String"}

      }
    end
  end
end

