# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ModuleItem < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :module_id, resolve_type("Integer")
    attribute :position, resolve_type("Integer")
    attribute :title, resolve_type("String")
    attribute :indent, resolve_type("Integer")
    attribute :type, resolve_type("String")
    attribute :content_id, resolve_type("Integer")
    attribute :html_url, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :page_url, resolve_type("String")
    attribute :external_url, resolve_type("String")
    attribute :new_tab, resolve_type(nil)
    attribute :completion_requirement, resolve_type("CompletionRequirement")
    attribute :content_details, resolve_type("ContentDetails")
    
  end
end

