require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Module < ModelBase
    attr_accessor :id, :workflow_state, :position, :name, :unlock_at, :require_sequential_progress, :prerequisite_module_ids, :items_count, :items_url, :items, :state, :completed_at, :publish_final_grade


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :workflow_state => {:external => "workflow_state", :container => false, :type => nil},
        :position => {:external => "position", :container => false, :type => nil},
        :name => {:external => "name", :container => false, :type => nil},
        :unlock_at => {:external => "unlock_at", :container => false, :type => nil},
        :require_sequential_progress => {:external => "require_sequential_progress", :container => false, :type => nil},
        :prerequisite_module_ids => {:external => "prerequisite_module_ids", :container => false, :type => nil},
        :items_count => {:external => "items_count", :container => false, :type => nil},
        :items_url => {:external => "items_url", :container => false, :type => nil},
        :items => {:external => "items", :container => false, :type => nil},
        :state => {:external => "state", :container => false, :type => nil},
        :completed_at => {:external => "completed_at", :container => false, :type => nil},
        :publish_final_grade => {:external => "publish_final_grade", :container => false, :type => nil}

      }
    end
  end
end

