require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ModuleItem < ModelBase
    attr_accessor :id, :module_id, :position, :title, :indent, :type, :content_id, :html_url, :url, :page_url, :external_url, :new_tab, :completion_requirement, :content_details


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :module_id => {:external => "module_id", :container => false, :type => "Integer"},
        :position => {:external => "position", :container => false, :type => "Integer"},
        :title => {:external => "title", :container => false, :type => "String"},
        :indent => {:external => "indent", :container => false, :type => "Integer"},
        :type => {:external => "type", :container => false, :type => "String"},
        :content_id => {:external => "content_id", :container => false, :type => "Integer"},
        :html_url => {:external => "html_url", :container => false, :type => "String"},
        :url => {:external => "url", :container => false, :type => "String"},
        :page_url => {:external => "page_url", :container => false, :type => "String"},
        :external_url => {:external => "external_url", :container => false, :type => "String"},
        :new_tab => {:external => "new_tab", :container => false, :type => nil},
        :completion_requirement => {:external => "completion_requirement", :container => false, :type => "CompletionRequirement"},
        :content_details => {:external => "content_details", :container => false, :type => "ContentDetails"}

      }
    end
  end
end

