# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Module < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :position, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :unlock_at, resolve_type("DateTime")
    attribute :require_sequential_progress, resolve_type(nil)
    attribute :prerequisite_module_ids, resolve_type("Integer", collection: true)
    attribute :items_count, resolve_type("Integer")
    attribute :items_url, resolve_type("String")
    attribute :items, resolve_type("ModuleItem", collection: true)
    attribute :state, resolve_type("String")
    attribute :completed_at, resolve_type("DateTime")
    attribute :publish_final_grade, resolve_type(nil)
    
  end
end

