# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ModuleItemSequence < ModelBase
    include Virtus.model(finalize: false)

    attribute :items, resolve_type("String")
    attribute :modules, resolve_type("Module", collection: true)
    
  end
end

