require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ModuleItemSequence < ModelBase
    attr_accessor :items, :modules


    def self.attribute_map
      {
        :items => {:external => "items", :container => false, :type => "String"},
        :modules => {:external => "modules", :container => true, :type => "Module"}

      }
    end
  end
end

