require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class NeedsGradingCount < ModelBase
    attr_accessor :section_id, :needs_grading_count


    def self.attribute_map
      {
        :section_id => {:external => "section_id", :container => false, :type => "String"},
        :needs_grading_count => {:external => "needs_grading_count", :container => false, :type => "Integer"}

      }
    end
  end
end

