# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class NeedsGradingCount < ModelBase
    include Virtus.model(finalize: false)

    attribute :section_id, resolve_type("String")
    attribute :needs_grading_count, resolve_type("Integer")
    
  end
end

