require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class NotificationPreference < ModelBase
    attr_accessor :href, :notification, :category, :frequency


    def self.attribute_map
      {
        :href => {:external => "href", :container => false, :type => "String"},
        :notification => {:external => "notification", :container => false, :type => "String"},
        :category => {:external => "category", :container => false, :type => "String"},
        :frequency => {:external => "frequency", :container => false, :type => "String"}

      }
    end
  end
end

