# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class NotificationPreference < ModelBase
    include Virtus.model(finalize: false)

    attribute :href, resolve_type("String")
    attribute :notification, resolve_type("String")
    attribute :category, resolve_type("String")
    attribute :frequency, resolve_type("String")
    
  end
end

