# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class OriginalityReport < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :file_id, resolve_type("Integer")
    attribute :originality_score, resolve_type("Float")
    attribute :originality_report_file_id, resolve_type("Integer")
    attribute :originality_report_url, resolve_type("String")
    attribute :tool_setting, resolve_type("ToolSetting")
    
  end
end

