require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class OutcomeLink < ModelBase
    attr_accessor :url, :context_id, :context_type, :outcome_group, :outcome


    def self.attribute_map
      {
        :url => {:external => "url", :container => false, :type => "String"},
        :context_id => {:external => "context_id", :container => false, :type => "Integer"},
        :context_type => {:external => "context_type", :container => false, :type => "String"},
        :outcome_group => {:external => "outcome_group", :container => false, :type => "OutcomeGroup"},
        :outcome => {:external => "outcome", :container => false, :type => "OutcomeGroup"}

      }
    end
  end
end

