require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Outcome < ModelBase
    attr_accessor :id, :url, :context_id, :context_type, :title, :description, :vendor_guid, :points_possible, :mastery_points, :ratings, :can_edit


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :url => {:external => "url", :container => false, :type => "String"},
        :context_id => {:external => "context_id", :container => false, :type => "Integer"},
        :context_type => {:external => "context_type", :container => false, :type => "String"},
        :title => {:external => "title", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"},
        :vendor_guid => {:external => "vendor_guid", :container => false, :type => "String"},
        :points_possible => {:external => "points_possible", :container => false, :type => "Integer"},
        :mastery_points => {:external => "mastery_points", :container => false, :type => "Integer"},
        :ratings => {:external => "ratings", :container => true, :type => "RubricRating"},
        :can_edit => {:external => "can_edit", :container => false, :type => nil}

      }
    end
  end
end

