require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class PageRevision < ModelBase
    attr_accessor :revision_id, :updated_at, :edited_by, :url, :title, :body


    def self.attribute_map
      {
        :revision_id => {:external => "revision_id", :container => false, :type => nil},
        :updated_at => {:external => "updated_at", :container => false, :type => nil},
        :edited_by => {:external => "edited_by", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :title => {:external => "title", :container => false, :type => nil},
        :body => {:external => "body", :container => false, :type => nil}

      }
    end
  end
end

