# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PageViewLinks < ModelBase
    include Virtus.model(finalize: false)

    attribute :user, resolve_type(nil)
    attribute :context, resolve_type(nil)
    attribute :asset, resolve_type(nil)
    attribute :real_user, resolve_type(nil)
    attribute :account, resolve_type(nil)
    
  end
end

