require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class PageViewLinks < ModelBase
    attr_accessor :id, :description, :properties


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :description => {:external => "description", :container => false, :type => nil},
        :properties => {:external => "properties", :container => false, :type => nil}

      }
    end
  end
end

