# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PageRevision < ModelBase
    include Virtus.model(finalize: false)

    attribute :revision_id, resolve_type("Integer")
    attribute :updated_at, resolve_type("DateTime")
    attribute :latest, resolve_type(nil)
    attribute :edited_by, resolve_type("User")
    attribute :url, resolve_type("String")
    attribute :title, resolve_type("String")
    attribute :body, resolve_type("String")
    
  end
end

