# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Page < ModelBase
    include Virtus.model(finalize: false)

    attribute :url, resolve_type("String")
    attribute :title, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :hide_from_students, resolve_type(nil)
    attribute :editing_roles, resolve_type("String")
    attribute :last_edited_by, resolve_type("User")
    attribute :body, resolve_type("String")
    attribute :published, resolve_type(nil)
    attribute :front_page, resolve_type(nil)
    attribute :locked_for_user, resolve_type(nil)
    attribute :lock_info, resolve_type("LockInfo")
    attribute :lock_explanation, resolve_type("String")
    
  end
end

