require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class PageViewLinks < ModelBase
    attr_accessor :user, :context, :asset, :real_user, :account


    def self.attribute_map
      {
        :user => {:external => "user", :container => false, :type => nil},
        :context => {:external => "context", :container => false, :type => nil},
        :asset => {:external => "asset", :container => false, :type => nil},
        :real_user => {:external => "real_user", :container => false, :type => nil},
        :account => {:external => "account", :container => false, :type => nil}

      }
    end
  end
end

