require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class PageView < ModelBase
    attr_accessor :id, :url, :context_type, :asset_type, :controller, :action, :contributed, :interaction_seconds, :created_at, :user_request, :render_time, :user_agent, :participated, :http_method, :remote_ip, :links


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :context_type => {:external => "context_type", :container => false, :type => nil},
        :asset_type => {:external => "asset_type", :container => false, :type => nil},
        :controller => {:external => "controller", :container => false, :type => nil},
        :action => {:external => "action", :container => false, :type => nil},
        :contributed => {:external => "contributed", :container => false, :type => nil},
        :interaction_seconds => {:external => "interaction_seconds", :container => false, :type => nil},
        :created_at => {:external => "created_at", :container => false, :type => "Datetime"},
        :user_request => {:external => "user_request", :container => false, :type => nil},
        :render_time => {:external => "render_time", :container => false, :type => nil},
        :user_agent => {:external => "user_agent", :container => false, :type => nil},
        :participated => {:external => "participated", :container => false, :type => nil},
        :http_method => {:external => "http_method", :container => false, :type => nil},
        :remote_ip => {:external => "remote_ip", :container => false, :type => nil},
        :links => {:external => "links", :container => false, :type => "PageViewLinks"}

      }
    end
  end
end

