# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PageView < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :context_type, resolve_type("String")
    attribute :asset_type, resolve_type("String")
    attribute :controller, resolve_type("String")
    attribute :action, resolve_type("String")
    attribute :contributed, resolve_type(nil)
    attribute :interaction_seconds, resolve_type("Float")
    attribute :created_at, resolve_type("DateTime")
    attribute :user_request, resolve_type(nil)
    attribute :render_time, resolve_type("Float")
    attribute :user_agent, resolve_type("String")
    attribute :participated, resolve_type(nil)
    attribute :http_method, resolve_type("String")
    attribute :remote_ip, resolve_type("String")
    attribute :links, resolve_type("PageViewLinks")
    
  end
end

