# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PeerReview < ModelBase
    include Virtus.model(finalize: false)

    attribute :assessor_id, resolve_type("Integer")
    attribute :asset_id, resolve_type("Integer")
    attribute :asset_type, resolve_type("String")
    attribute :id, resolve_type("Integer")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :user, resolve_type("String")
    attribute :assessor, resolve_type("String")
    attribute :submission_comments, resolve_type("String")
    
  end
end

