# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PlannerNote < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :title, resolve_type("String")
    attribute :description, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :course_id, resolve_type("Integer")
    attribute :todo_date, resolve_type("DateTime")
    attribute :linked_object_type, resolve_type("String")
    attribute :linked_object_id, resolve_type("Integer")
    attribute :linked_object_html_url, resolve_type("String")
    attribute :linked_object_url, resolve_type("String")
    
  end
end

