# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class PlannerOverride < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :plannable_type, resolve_type("String")
    attribute :plannable_id, resolve_type("Integer")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :marked_complete, resolve_type(nil)
    attribute :dismissed, resolve_type(nil)
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :deleted_at, resolve_type("DateTime")
    
  end
end

