require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class PollChoice < ModelBase
    attr_accessor :id, :is_correct, :text


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :is_correct => {:external => "is_correct", :container => false, :type => nil},
        :text => {:external => "text", :container => false, :type => "String"}

      }
    end
  end
end

