require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Poll < ModelBase
    attr_accessor :id, :course, :title, :description


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :course => {:external => "course", :container => false, :type => "Course"},
        :title => {:external => "title", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"}

      }
    end
  end
end

