require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Profile < ModelBase
    attr_accessor :id, :name, :short_name, :sortable_name, :title, :bio, :primary_email, :login_id, :sis_user_id, :sis_login_id, :avatar_url, :calendar, :time_zone


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :name => {:external => "name", :container => false, :type => "String"},
        :short_name => {:external => "short_name", :container => false, :type => "String"},
        :sortable_name => {:external => "sortable_name", :container => false, :type => "String"},
        :title => {:external => "title", :container => false, :type => "String"},
        :bio => {:external => "bio", :container => false, :type => "String"},
        :primary_email => {:external => "primary_email", :container => false, :type => "String"},
        :login_id => {:external => "login_id", :container => false, :type => "String"},
        :sis_user_id => {:external => "sis_user_id", :container => false, :type => "String"},
        :sis_login_id => {:external => "sis_login_id", :container => false, :type => "String"},
        :avatar_url => {:external => "avatar_url", :container => false, :type => "String"},
        :calendar => {:external => "calendar", :container => false, :type => "CalendarLink"},
        :time_zone => {:external => "time_zone", :container => false, :type => "String"}

      }
    end
  end
end

