# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Profile < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :short_name, resolve_type("String")
    attribute :sortable_name, resolve_type("String")
    attribute :title, resolve_type("String")
    attribute :bio, resolve_type("String")
    attribute :primary_email, resolve_type("String")
    attribute :login_id, resolve_type("String")
    attribute :sis_user_id, resolve_type("String")
    attribute :sis_login_id, resolve_type("String")
    attribute :avatar_url, resolve_type("String")
    attribute :calendar, resolve_type("CalendarLink")
    attribute :time_zone, resolve_type("String")
    attribute :locale, resolve_type("String")
    
  end
end

