# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Progress < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :context_id, resolve_type("Integer")
    attribute :context_type, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    attribute :tag, resolve_type("String")
    attribute :completion, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :message, resolve_type("String")
    attribute :url, resolve_type("String")
    
  end
end

