require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Progress < ModelBase
    attr_accessor :id, :context_id, :context_type, :user_id, :tag, :completion, :workflow_state, :created_at, :updated_at, :message, :url


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :context_id => {:external => "context_id", :container => false, :type => "Integer"},
        :context_type => {:external => "context_type", :container => false, :type => "String"},
        :user_id => {:external => "user_id", :container => false, :type => "Integer"},
        :tag => {:external => "tag", :container => false, :type => "String"},
        :completion => {:external => "completion", :container => false, :type => "Integer"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"},
        :message => {:external => "message", :container => false, :type => "String"},
        :url => {:external => "url", :container => false, :type => "String"}

      }
    end
  end
end

