# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ProvisionalGrade < ModelBase
    include Virtus.model(finalize: false)

    attribute :provisional_grade_id, resolve_type("Integer")
    attribute :score, resolve_type("Integer")
    attribute :grade, resolve_type("String")
    attribute :grade_matches_current_submission, resolve_type(nil)
    attribute :graded_at, resolve_type("DateTime")
    attribute :final, resolve_type(nil)
    attribute :speedgrader_url, resolve_type("String")
    
  end
end

