# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizPermissions < ModelBase
    include Virtus.model(finalize: false)

    attribute :read, resolve_type(nil)
    attribute :submit, resolve_type(nil)
    attribute :create, resolve_type(nil)
    attribute :manage, resolve_type(nil)
    attribute :read_statistics, resolve_type(nil)
    attribute :review_grades, resolve_type(nil)
    attribute :update, resolve_type(nil)
    
  end
end

