# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizAssignmentOverrideSet < ModelBase
    include Virtus.model(finalize: false)

    attribute :quiz_id, resolve_type("String")
    attribute :due_dates, resolve_type("QuizAssignmentOverride")
    attribute :all_dates, resolve_type("QuizAssignmentOverride")
    
  end
end

