# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizAssignmentOverrideSetContainer < ModelBase
    include Virtus.model(finalize: false)

    attribute :quiz_assignment_overrides, resolve_type("QuizAssignmentOverrideSet", collection: true)
    
  end
end

