require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class QuizAssignmentOverrideSet < ModelBase
    attr_accessor :quiz_id, :due_dates, :all_dates


    def self.attribute_map
      {
        :quiz_id => {:external => "quiz_id", :container => false, :type => "String"},
        :due_dates => {:external => "due_dates", :container => false, :type => "QuizAssignmentOverride"},
        :all_dates => {:external => "all_dates", :container => false, :type => "QuizAssignmentOverride"}

      }
    end
  end
end

