# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizQuestion < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type(nil)
    attribute :quiz_id, resolve_type(nil)
    attribute :position, resolve_type(nil)
    attribute :question_name, resolve_type("String")
    attribute :question_type, resolve_type("String")
    attribute :question_text, resolve_type("String")
    attribute :points_possible, resolve_type(nil)
    attribute :correct_comments, resolve_type("String")
    attribute :incorrect_comments, resolve_type("String")
    attribute :neutral_comments, resolve_type("String")
    attribute :answers, resolve_type("Answer", collection: true)
    
  end
end

