require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class QuizPermissions < ModelBase
    attr_accessor :read, :submit, :create, :manage, :read_statistics, :review_grades, :update


    def self.attribute_map
      {
        :read => {:external => "read", :container => false, :type => nil},
        :submit => {:external => "submit", :container => false, :type => nil},
        :create => {:external => "create", :container => false, :type => nil},
        :manage => {:external => "manage", :container => false, :type => nil},
        :read_statistics => {:external => "read_statistics", :container => false, :type => nil},
        :review_grades => {:external => "review_grades", :container => false, :type => nil},
        :update => {:external => "update", :container => false, :type => nil}

      }
    end
  end
end

