require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class QuizQuestion < ModelBase
    attr_accessor :id, :quiz_id, :position, :question_name, :question_type, :question_text, :points_possible, :correct_comments, :incorrect_comments, :neutral_comments, :answers


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => nil},
        :quiz_id => {:external => "quiz_id", :container => false, :type => nil},
        :position => {:external => "position", :container => false, :type => nil},
        :question_name => {:external => "question_name", :container => false, :type => nil},
        :question_type => {:external => "question_type", :container => false, :type => nil},
        :question_text => {:external => "question_text", :container => false, :type => nil},
        :points_possible => {:external => "points_possible", :container => false, :type => nil},
        :correct_comments => {:external => "correct_comments", :container => false, :type => nil},
        :incorrect_comments => {:external => "incorrect_comments", :container => false, :type => nil},
        :neutral_comments => {:external => "neutral_comments", :container => false, :type => nil},
        :answers => {:external => "answers", :container => true, :type => nil}

      }
    end
  end
end

