# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizReport < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :quiz_id, resolve_type("Integer")
    attribute :report_type, resolve_type("String")
    attribute :readable_type, resolve_type("String")
    attribute :includes_all_versions, resolve_type(nil)
    attribute :anonymous, resolve_type(nil)
    attribute :generatable, resolve_type(nil)
    attribute :created_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :url, resolve_type("String")
    attribute :file, resolve_type("File")
    attribute :progress_url, resolve_type("String")
    attribute :progress, resolve_type("Progress")
    
  end
end

