# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class QuizSubmissionQuestion < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type(nil)
    attribute :flagged, resolve_type(nil)
    attribute :answer, resolve_type("String")
    attribute :answers, resolve_type("String", collection: true)
    
  end
end

