require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class ReportParameters < ModelBase
    attr_accessor :enrollment_term_id, :include_deleted, :course_id, :order, :users, :accounts, :terms, :courses, :sections, :enrollments, :groups, :xlist, :sis_terms_csv, :sis_accounts_csv, :include_enrollment_state, :enrollment_state____, :start_at, :end_at


    def self.attribute_map
      {
        :enrollment_term_id => {:external => "enrollment_term_id", :container => false, :type => "Integer"},
        :include_deleted => {:external => "include_deleted", :container => false, :type => nil},
        :course_id => {:external => "course_id", :container => false, :type => "Integer"},
        :order => {:external => "order", :container => false, :type => "String"},
        :users => {:external => "users", :container => false, :type => nil},
        :accounts => {:external => "accounts", :container => false, :type => nil},
        :terms => {:external => "terms", :container => false, :type => nil},
        :courses => {:external => "courses", :container => false, :type => nil},
        :sections => {:external => "sections", :container => false, :type => nil},
        :enrollments => {:external => "enrollments", :container => false, :type => nil},
        :groups => {:external => "groups", :container => false, :type => nil},
        :xlist => {:external => "xlist", :container => false, :type => nil},
        :sis_terms_csv => {:external => "sis_terms_csv", :container => false, :type => "Integer"},
        :sis_accounts_csv => {:external => "sis_accounts_csv", :container => false, :type => "Integer"},
        :include_enrollment_state => {:external => "include_enrollment_state", :container => false, :type => nil},
        :enrollment_state____ => {:external => "enrollment_state[]", :container => false, :type => "String"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :end_at => {:external => "end_at", :container => false, :type => "DateTime"}

      }
    end
  end
end

