# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class ReportParameters < ModelBase
    include Virtus.model(finalize: false)

    attribute :enrollment_term_id, resolve_type("Integer")
    attribute :include_deleted, resolve_type(nil)
    attribute :course_id, resolve_type("Integer")
    attribute :order, resolve_type("String")
    attribute :users, resolve_type(nil)
    attribute :accounts, resolve_type(nil)
    attribute :terms, resolve_type(nil)
    attribute :courses, resolve_type(nil)
    attribute :sections, resolve_type(nil)
    attribute :enrollments, resolve_type(nil)
    attribute :groups, resolve_type(nil)
    attribute :xlist, resolve_type(nil)
    attribute :sis_terms_csv, resolve_type("Integer")
    attribute :sis_accounts_csv, resolve_type("Integer")
    attribute :include_enrollment_state, resolve_type(nil)
    attribute :enrollment_state____, resolve_type("String")
    attribute :start_at, resolve_type("DateTime")
    attribute :end_at, resolve_type("DateTime")
    
  end
end

