require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Report < ModelBase
    attr_accessor :id, :report, :file_url, :status, :parameters, :progress


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :report => {:external => "report", :container => false, :type => "String"},
        :file_url => {:external => "file_url", :container => false, :type => "String"},
        :status => {:external => "status", :container => false, :type => "String"},
        :parameters => {:external => "parameters", :container => false, :type => "ReportParameters"},
        :progress => {:external => "progress", :container => false, :type => "String"}

      }
    end
  end
end

