# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Report < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :report, resolve_type("String")
    attribute :file_url, resolve_type("String")
    attribute :attachment, resolve_type("File")
    attribute :status, resolve_type("String")
    attribute :parameters, resolve_type("ReportParameters")
    attribute :progress, resolve_type("Integer")
    attribute :current_line, resolve_type("Integer")
    
  end
end

