require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class RubricCriteria < ModelBase
    attr_accessor :points, :id, :description, :ratings


    def self.attribute_map
      {
        :points => {:external => "points", :container => false, :type => "Integer"},
        :id => {:external => "id", :container => false, :type => "String"},
        :description => {:external => "description", :container => false, :type => "String"},
        :ratings => {:external => "ratings", :container => true, :type => "RubricRating"}

      }
    end
  end
end

