# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Rubric < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :title, resolve_type("String")
    attribute :context_id, resolve_type("Integer")
    attribute :context_type, resolve_type("String")
    attribute :points_possible, resolve_type("Integer")
    attribute :reusable, resolve_type(nil)
    attribute :read_only, resolve_type(nil)
    attribute :free_form_criterion_comments, resolve_type(nil)
    attribute :hide_score_total, resolve_type(nil)
    attribute :assessments, resolve_type("RubricAssessment", collection: true)
    
  end
end

