# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class RubricAssessment < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :rubric_id, resolve_type("Integer")
    attribute :rubric_association_id, resolve_type("Integer")
    attribute :score, resolve_type("Integer")
    attribute :artifact_type, resolve_type("String")
    attribute :artifact_id, resolve_type("Integer")
    attribute :artifact_attempt, resolve_type("Integer")
    attribute :assessment_type, resolve_type("String")
    attribute :assessor_id, resolve_type("Integer")
    attribute :data, resolve_type("Object", collection: true)
    attribute :comments, resolve_type("String", collection: true)
    
  end
end

