# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class RubricRating < ModelBase
    include Virtus.model(finalize: false)

    attribute :points, resolve_type("Integer")
    attribute :id, resolve_type("String")
    attribute :description, resolve_type("String")
    
  end
end

