# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class SSOSettings < ModelBase
    include Virtus.model(finalize: false)

    attribute :login_handle_name, resolve_type("String")
    attribute :change_password_url, resolve_type("String")
    attribute :auth_discovery_url, resolve_type("String")
    attribute :unknown_user_url, resolve_type("String")
    
  end
end

