require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Section < ModelBase
    attr_accessor :id, :name, :sis_section_id, :integration_id, :sis_import_id, :course_id, :sis_course_id, :start_at, :end_at, :nonxlist_course_id


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :name => {:external => "name", :container => false, :type => "String"},
        :sis_section_id => {:external => "sis_section_id", :container => false, :type => "String"},
        :integration_id => {:external => "integration_id", :container => false, :type => "String"},
        :sis_import_id => {:external => "sis_import_id", :container => false, :type => "Integer"},
        :course_id => {:external => "course_id", :container => false, :type => "Integer"},
        :sis_course_id => {:external => "sis_course_id", :container => false, :type => "Integer"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :end_at => {:external => "end_at", :container => false, :type => "DateTime"},
        :nonxlist_course_id => {:external => "nonxlist_course_id", :container => false, :type => "Integer"}

      }
    end
  end
end

