# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Section < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :name, resolve_type("String")
    attribute :sis_section_id, resolve_type("String")
    attribute :integration_id, resolve_type("String")
    attribute :sis_import_id, resolve_type("Integer")
    attribute :course_id, resolve_type("Integer")
    attribute :sis_course_id, resolve_type("String")
    attribute :start_at, resolve_type("DateTime")
    attribute :end_at, resolve_type("DateTime")
    attribute :nonxlist_course_id, resolve_type("Integer")
    attribute :total_students, resolve_type("Integer")
    
  end
end

