require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SisImport < ModelBase
    attr_accessor :id, :created_at, :ended_at, :updated_at, :workflow_state, :data, :progress, :processing_warnings, :processing_errors, :batch_mode, :batch_mode_term_id, :override_sis_stickiness, :add_sis_stickiness, :clear_sis_stickiness


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :ended_at => {:external => "ended_at", :container => false, :type => "DateTime"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :data => {:external => "data", :container => false, :type => "SisImportData"},
        :progress => {:external => "progress", :container => false, :type => "String"},
        :processing_warnings => {:external => "processing_warnings", :container => true, :type => "Array"},
        :processing_errors => {:external => "processing_errors", :container => true, :type => "Array"},
        :batch_mode => {:external => "batch_mode", :container => false, :type => nil},
        :batch_mode_term_id => {:external => "batch_mode_term_id", :container => false, :type => "String"},
        :override_sis_stickiness => {:external => "override_sis_stickiness", :container => false, :type => nil},
        :add_sis_stickiness => {:external => "add_sis_stickiness", :container => false, :type => nil},
        :clear_sis_stickiness => {:external => "clear_sis_stickiness", :container => false, :type => nil}

      }
    end
  end
end

