require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SisImportData < ModelBase
    attr_accessor :import_type, :supplied_batches, :counts


    def self.attribute_map
      {
        :import_type => {:external => "import_type", :container => false, :type => "String"},
        :supplied_batches => {:external => "supplied_batches", :container => true, :type => "String"},
        :counts => {:external => "counts", :container => false, :type => "SisImportCounts"}

      }
    end
  end
end

