# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class SisImport < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :created_at, resolve_type("DateTime")
    attribute :ended_at, resolve_type("DateTime")
    attribute :updated_at, resolve_type("DateTime")
    attribute :workflow_state, resolve_type("String")
    attribute :data, resolve_type("SisImportData")
    attribute :progress, resolve_type("String")
    attribute :errors_attachment, resolve_type("File")
    attribute :processing_warnings, resolve_type("Array", collection: true)
    attribute :user, resolve_type("User")
    attribute :processing_errors, resolve_type("Array", collection: true)
    attribute :batch_mode, resolve_type(nil)
    attribute :batch_mode_term_id, resolve_type("String")
    attribute :multi_term_batch_mode, resolve_type(nil)
    attribute :override_sis_stickiness, resolve_type(nil)
    attribute :add_sis_stickiness, resolve_type(nil)
    attribute :clear_sis_stickiness, resolve_type(nil)
    attribute :diffing_data_set_identifier, resolve_type("String")
    attribute :diffed_against_import_id, resolve_type("Integer")
    
  end
end

