# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class SisImportCounts < ModelBase
    include Virtus.model(finalize: false)

    attribute :accounts, resolve_type("Integer")
    attribute :terms, resolve_type("Integer")
    attribute :abstract_courses, resolve_type("Integer")
    attribute :courses, resolve_type("Integer")
    attribute :sections, resolve_type("Integer")
    attribute :xlists, resolve_type("Integer")
    attribute :users, resolve_type("Integer")
    attribute :enrollments, resolve_type("Integer")
    attribute :groups, resolve_type("Integer")
    attribute :group_memberships, resolve_type("Integer")
    attribute :grade_publishing_results, resolve_type("Integer")
    
  end
end

