require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SisImportCounts < ModelBase
    attr_accessor :accounts, :terms, :abstract_courses, :courses, :sections, :xlists, :users, :enrollments, :groups, :group_memberships, :grade_publishing_results


    def self.attribute_map
      {
        :accounts => {:external => "accounts", :container => false, :type => "Integer"},
        :terms => {:external => "terms", :container => false, :type => "Integer"},
        :abstract_courses => {:external => "abstract_courses", :container => false, :type => "Integer"},
        :courses => {:external => "courses", :container => false, :type => "Integer"},
        :sections => {:external => "sections", :container => false, :type => "Integer"},
        :xlists => {:external => "xlists", :container => false, :type => "Integer"},
        :users => {:external => "users", :container => false, :type => "Integer"},
        :enrollments => {:external => "enrollments", :container => false, :type => "Integer"},
        :groups => {:external => "groups", :container => false, :type => "Integer"},
        :group_memberships => {:external => "group_memberships", :container => false, :type => "Integer"},
        :grade_publishing_results => {:external => "grade_publishing_results", :container => false, :type => "Integer"}

      }
    end
  end
end

