# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class SubmissionVersion < ModelBase
    include Virtus.model(finalize: false)

    attribute :assignment_id, resolve_type("Integer")
    attribute :assignment_name, resolve_type("String")
    attribute :body, resolve_type("String")
    attribute :current_grade, resolve_type("String")
    attribute :current_graded_at, resolve_type("DateTime")
    attribute :current_grader, resolve_type("String")
    attribute :grade_matches_current_submission, resolve_type(nil)
    attribute :graded_at, resolve_type("DateTime")
    attribute :grader, resolve_type("String")
    attribute :grader_id, resolve_type("Integer")
    attribute :id, resolve_type("Integer")
    attribute :new_grade, resolve_type("String")
    attribute :new_graded_at, resolve_type("DateTime")
    attribute :new_grader, resolve_type("String")
    attribute :previous_grade, resolve_type("String")
    attribute :previous_graded_at, resolve_type("DateTime")
    attribute :previous_grader, resolve_type("String")
    attribute :score, resolve_type("Integer")
    attribute :user_name, resolve_type("String")
    attribute :submission_type, resolve_type("String")
    attribute :url, resolve_type("String")
    attribute :user_id, resolve_type("Integer")
    attribute :workflow_state, resolve_type("String")
    
  end
end

