require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SubmissionHistory < ModelBase
    attr_accessor :submission_id, :versions


    def self.attribute_map
      {
        :submission_id => {:external => "submission_id", :container => false, :type => "Integer"},
        :versions => {:external => "versions", :container => true, :type => "Integer"}

      }
    end
  end
end

