# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class SubmissionComment < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type("Integer")
    attribute :author_id, resolve_type("Integer")
    attribute :author_name, resolve_type("String")
    attribute :comment, resolve_type("String")
    attribute :created_at, resolve_type("DateTime")
    attribute :media_comment, resolve_type("MediaComment")
    
  end
end

