require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SubmissionVersion < ModelBase
    attr_accessor :assignment_id, :assignment_name, :body, :current_grade, :current_graded_at, :current_grader, :grade_matches_current_submission, :graded_at, :grader, :grader_id, :id, :new_grade, :new_graded_at, :new_grader, :previous_grade, :previous_graded_at, :previous_grader, :score, :user_name, :submission_type, :url, :user_id, :workflow_state


    def self.attribute_map
      {
        :assignment_id => {:external => "assignment_id", :container => false, :type => nil},
        :assignment_name => {:external => "assignment_name", :container => false, :type => nil},
        :body => {:external => "body", :container => false, :type => nil},
        :current_grade => {:external => "current_grade", :container => false, :type => nil},
        :current_graded_at => {:external => "current_graded_at", :container => false, :type => "Date"},
        :current_grader => {:external => "current_grader", :container => false, :type => nil},
        :grade_matches_current_submission => {:external => "grade_matches_current_submission", :container => false, :type => nil},
        :graded_at => {:external => "graded_at", :container => false, :type => "Date"},
        :grader => {:external => "grader", :container => false, :type => nil},
        :grader_id => {:external => "grader_id", :container => false, :type => nil},
        :id => {:external => "id", :container => false, :type => nil},
        :new_grade => {:external => "new_grade", :container => false, :type => nil},
        :new_graded_at => {:external => "new_graded_at", :container => false, :type => "Date"},
        :new_grader => {:external => "new_grader", :container => false, :type => nil},
        :previous_grade => {:external => "previous_grade", :container => false, :type => nil},
        :previous_graded_at => {:external => "previous_graded_at", :container => false, :type => "Date"},
        :previous_grader => {:external => "previous_grader", :container => false, :type => nil},
        :score => {:external => "score", :container => false, :type => nil},
        :user_name => {:external => "user_name", :container => false, :type => nil},
        :submission_type => {:external => "submission_type", :container => false, :type => nil},
        :url => {:external => "url", :container => false, :type => nil},
        :user_id => {:external => "user_id", :container => false, :type => nil},
        :workflow_state => {:external => "workflow_state", :container => false, :type => nil}

      }
    end
  end
end

