# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class Tab < ModelBase
    include Virtus.model(finalize: false)

    attribute :html_url, resolve_type("String")
    attribute :id, resolve_type("String")
    attribute :label, resolve_type("String")
    attribute :type, resolve_type("String")
    attribute :hidden, resolve_type(nil)
    attribute :visibility, resolve_type("String")
    attribute :position, resolve_type("Integer")
    
  end
end

