require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Tab < ModelBase
    attr_accessor :html_url, :id, :label, :type, :hidden, :visibility, :position


    def self.attribute_map
      {
        :html_url => {:external => "html_url", :container => false, :type => "String"},
        :id => {:external => "id", :container => false, :type => "String"},
        :label => {:external => "label", :container => false, :type => "String"},
        :type => {:external => "type", :container => false, :type => "String"},
        :hidden => {:external => "hidden", :container => false, :type => nil},
        :visibility => {:external => "visibility", :container => false, :type => "String"},
        :position => {:external => "position", :container => false, :type => "Integer"}

      }
    end
  end
end

