require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class Term < ModelBase
    attr_accessor :id, :name, :start_at, :end_at


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :name => {:external => "name", :container => false, :type => "String"},
        :start_at => {:external => "start_at", :container => false, :type => "DateTime"},
        :end_at => {:external => "end_at", :container => false, :type => "DateTime"}

      }
    end
  end
end

