require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class TurnitinSettings < ModelBase
    attr_accessor :originality_report_visibility, :s_paper_check, :internet_check, :journal_check, :exclude_biblio, :exclude_quoted, :exclude_small_matches_type, :exclude_small_matches_value


    def self.attribute_map
      {
        :originality_report_visibility => {:external => "originality_report_visibility", :container => false, :type => "String"},
        :s_paper_check => {:external => "s_paper_check", :container => false, :type => nil},
        :internet_check => {:external => "internet_check", :container => false, :type => nil},
        :journal_check => {:external => "journal_check", :container => false, :type => nil},
        :exclude_biblio => {:external => "exclude_biblio", :container => false, :type => nil},
        :exclude_quoted => {:external => "exclude_quoted", :container => false, :type => nil},
        :exclude_small_matches_type => {:external => "exclude_small_matches_type", :container => false, :type => "String"},
        :exclude_small_matches_value => {:external => "exclude_small_matches_value", :container => false, :type => "Integer"}

      }
    end
  end
end

