# This is an autogenerated file. See readme.md.
require 'pandarus/model_base'

module Pandarus
  class User < ModelBase
    include Virtus.model(finalize: false)

    attribute :id, resolve_type(nil)
    attribute :name, resolve_type("String")
    attribute :sortable_name, resolve_type("String")
    attribute :short_name, resolve_type("String")
    attribute :sis_user_id, resolve_type("String")
    attribute :sis_import_id, resolve_type(nil)
    attribute :sis_login_id, resolve_type("String")
    attribute :login_id, resolve_type("String")
    attribute :avatar_url, resolve_type("String")
    attribute :enrollments, resolve_type("Enrollment", collection: true)
    attribute :email, resolve_type("String")
    attribute :locale, resolve_type("String")
    attribute :last_login, resolve_type("Date")
    attribute :time_zone, resolve_type("String")
    attribute :bio, resolve_type("String")
    
  end
end

